version: "3.9"
services:


  eureka:
    container_name: eureka
    build: .\EurekaServer
    ports:
      - "8761:8761"
    image: "eureka"
    environment:
      - eureka.client.server-url.default-zone=http://eureka:8761/eureka/

  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=miniprojet
    ports:
      - "3309:3306"
    restart: unless-stopped



  bloc:
    container_name: ServiceBloc
    build: ./microservice-bloc
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka
  foyer:
    container_name: ServiceFoyer
    build: ./microservice-foyer-main
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/foyer?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka
      - db-mysql

  chambre:
    container_name: ServiceChambre
    build: ./microservice-chambre-main
    ports:
      - "8082:8082"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka

  universite:
    container_name: ServiceUniversite
    build: ./microservice-universite-main
    ports:
      - "8910:8910"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/universite?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka
      - db-mysql

  reservation:
    container_name: ServiceReservation
    build: ./microservice-reservation-main
    ports:
      - "8091:8091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/gestionfoyer?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka
      - db-mysql

  apigateway:
    container_name: Api_Gateway_Server
    image: "apigatewayms"
    build: ./APIGateway
    ports:
      - "8089:8089"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    restart: unless-stopped
    depends_on:
      - eureka





